### PR TITLE
suggested new home/login/register

### PR DESCRIPTION
**Pull request by spidoosho**
Suggestion for new and more modern-loogin web pages. Functionality remained the same.

### CODE REVIEW

**Review by MichalKyjovsky — CHANGES_REQUESTED** [review]
Please move all Javascripts and CSSs to separated files.

**Comment by MichalKyjovsky** [comment]
You have several conflicts, please wait when @JanKleprlik merges his work, pull the changes, and resolve the conflicts.

**Comment by spidoosho** [comment]
Scripts and styles were moved to seperated files.

**Comment by spidoosho** [comment]
merge not successful

**Pull request closed without merging**
